worker-threads: 4
worker-fs-threads: 2
logger-level: info

is-testing: false

server-port: 8080

dbconnection: 'postgresql://fitness_tracker_user:password@localhost:5432/fitness_tracker_service_db_1'
mongo-connection: 'mongodb://localhost:27017/fitness_tracker_mongo'
